<?php

/**
 * @file
 * Primary module hooks for Spotify Integration module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme.
 */
function spotify_integration_theme($existing, $type, $theme, $path) {
  return [
    'spotify_block' => [
      'variables' => [
        'artists' => NULL,
      ],
    ],
    'spotify_profile' => [
      'variables' => [
        'artist' => NULL,
      ],
    ],
  ];
}
